CREATE TABLE IF NOT EXISTS "dataflr"(
    "Country" TEXT,
    "Subnational unit" TEXT,
    "teak" TEXT,
    "eucalyptus" TEXT,
    "other broadleaf" TEXT,
    "oak" TEXT,
    "pine" TEXT,
    "other conifer" TEXT,
    "Natural Regeneration" TEXT,
    "Mangrove Restoration - tree" TEXT,
    "Mangrove Restoration - shrub" TEXT,
    "Agroforestry" TEXT,
    "Average FLR 20y" TEXT,
    "Average plantation" TEXT,
    "Average mangrove" TEXT,
    "Coastal" TEXT,
    "NatRegen" TEXT,
    "real_teak" real,
    "real_eucalyptus" real,
    "real_otherbroadleaf" real,
    "real_naturalregeneration" real,
    "real_averageflr20y" real,
    "real_natregen" real,
    "real_oak" real,
    "real_mangroverestorationtree" real,
    "real_averageplantation" real,
    "real_otherconifer" real,
    "real_agroforestry" real,
    "real_coastal" real,
    "real_pine" real,
    "real_mangroverestorationshrub" real,
    "real_averagemangrove" real
);

CREATE TABLE datahectare (
    id int primary key,
    flrtype txt,
    projectname txt,
    country txt,
    state txt,
    plantedspecies txt,
    year int,
    hectares real
);

CREATE TABLE user (
    uid txt primary key,
    email txt,
    emailVerified int,
    displayName txt,
    isAnonymous int,
    photoURL txt,
    providerId txt,
    providerUID txt,
    refreshToken txt,
    accessToken txt,
    tokenExpirationTime int,
    createdAt int,
    lastLoginAt int,
    apiKey txt,
    appName txt
);